SELECT Y.CATEGORY,	   
	   DENSE_RANK() OVER (ORDER BY Y.CATEGORY) ||'.'||ROW_NUMBER() OVER (PARTITION BY Y.CATEGORY ORDER BY X.QUESTIONID) SLNO, 
	   X.QUESTION_TITLE,   
	   NVL(MAX(DECODE(ANSWER1VALUE,'1',PESRCENTAGE)),'0 %') OPTION1,
	   NVL(MAX(DECODE(ANSWER1VALUE,'2',PESRCENTAGE)),'0 %') OPTION2,
	   NVL(MAX(DECODE(ANSWER1VALUE,'3',PESRCENTAGE)),'0 %') OPTION3,
	   NVL(MAX(DECODE(ANSWER1VALUE,'4',PESRCENTAGE)),'0 %') OPTION4,
	   NVL(MAX(DECODE(ANSWER1VALUE,'5',PESRCENTAGE)),'0 %') OPTION5,
	   NVL(MAX(DECODE(ANSWER1VALUE,'0',PESRCENTAGE)),'0 %') OPTION0 
FROM 
(SELECT   QUESTION_TITLE, QUESTIONID, TO_NUMBER(TRIM(ANSWER1VALUE)) ANSWER1VALUE,
                          COUNT (TRIM(ANSWER1VALUE)) ANSWERCOUNT,
                             ROUND
                                (  RATIO_TO_REPORT (COUNT (TRIM(ANSWER1VALUE))) OVER (PARTITION BY QUESTIONID)
                                 * 100,
                                 2
                                )
                          || ' %' PESRCENTAGE
                     FROM RESPONSE_DETAILS					 
                 GROUP BY QUESTION_TITLE, QUESTIONID, ANSWER1VALUE) X,QUESTIONS Y
				 WHERE X.QUESTIONID = Y.QUESTIONID
				 GROUP BY QUESTION_TITLE,X.QUESTIONID,Y.CATEGORY
				
				

				